# Generated by Django 3.1.7 on 2021-03-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NumberPlateDetector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carentry',
            old_name='pub_date',
            new_name='enter_date',
        ),
        migrations.RenameField(
            model_name='carexit',
            old_name='pub_date',
            new_name='exit_date',
        ),
    ]
