# Generated by Django 3.1.7 on 2021-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumberPlateDetector', '0003_cardetails_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='carentry',
            name='enter_date',
            field=models.DateTimeField(),
        ),
    ]
